---
title: "BenchmarkStudy"
author: "Tomoya Ozawa"
date: "2023-03-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(MASS)
library(tidyverse)
library(strucchange)
library(segmented)
```

## Simulated data

```{r}
set.seed(123)
X_const <- matrix(rep(1, 100), nrow = 100)
X_1 <- mvrnorm(n = 100, mu = rep(0, 5), Sigma = diag(5))
X_2 <- mvrnorm(n = 100, mu = rep(0, 5), Sigma = diag(5))

X_1 <- cbind(X_const, X_1)
X_2 <- cbind(X_const, X_2)

Beta_1 <- matrix(rep(1, 6), nrow = 6)
Beta_2 <- matrix(c(1, -1, 0, -1, 0, 1), nrow = 6)
epsilon_1 <- rnorm(100, 0, 1)
epsilon_2 <- rnorm(100, 0, 1)

Y_1 <- X_1%*%Beta_1 + epsilon_1
Y_2 <- X_2%*%Beta_2 + epsilon_2

Y <- rbind(Y_1, Y_2)
X <- rbind(X_1, X_2)
```

```{r}
df_simulated <- cbind(Y, X) %>% 
  as.data.frame()

colnames(df_simulated) <- c("Y", "const", "X1", "X2", "X3", "X4", "X5")

df_simulated %>% 
  head()
```

```{r}
df_simulated %>% 
  mutate(time = row_number()) %>% 
  ggplot(mapping = aes(x = time, y = Y)) +
  geom_line()
```



## Benchmark Methods:



### Bai and Perron (2003)

- `breakpoints()` from [strucchange](https://cran.r-project.org/web/packages/strucchange/strucchange.pdf)


```{r}
result_Bai_Perron <- breakpoints(Y ~ X1 + X2 + X3 + X4 + X5, data = df_simulated)
result_Bai_Perron
```

```{r}
summary(result_Bai_Perron)
```


- BIC is used as criteria to choose the number of change points

```{r}
result_Bai_Perron %>% plot()
```




### Muggeo (2003)

- `segmented()` from [segmented](https://cran.r-project.org/web/packages/segmented/segmented.pdfted)

- I am not sure what `seg.Z` means. Document says `seg.Z` is the segmented variable, i.e. the continuous covariates understood to have a piecewise-linear relationship will be estimated


```{r}
df_simulated <- mutate(df_simulated,
                       time = row_number())
model_lm <- lm(Y ~ X1 + X2 + X3 + X4 + X5, data = df_simulated)
segmented(model_lm, seg.Z =  ~ time)
```

```{r}
df_simulated <- mutate(df_simulated,
                       time = row_number())
model_lm <- lm(Y ~ X1 + X2 + X3 + X4 + X5, data = df_simulated)
segmented(model_lm, seg.Z =   ~ X1 + X2 + X3 + X4 + X5)
```




